language: go

sudo: false

go:
  - "1.11.x"

script:
  - golangci-lint run -E golint -E goimports -E interfacer
  - go test -v -coverprofile=coverage.txt -covermode=atomic -race ./...

install: true

env:
  - GO111MODULE=on

before_script:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
