language: go
sudo: false

go:
  - 1.10
  - 1.11

before_script:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - go test -v -coverprofile=coverage.txt -covermode=atomic -race ./...


after_success:
  - bash <(curl -s https://codecov.io/bash)
