// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// TableProvisioner is an autogenerated mock type for the TableProvisioner type
type TableProvisioner struct {
	mock.Mock
}

// Calculate provides a mock function with given fields:
func (_m *TableProvisioner) Calculate() (int64, int64) {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func() int64); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(int64)
	}

	return r0, r1
}

// NeedsUpdate provides a mock function with given fields:
func (_m *TableProvisioner) NeedsUpdate() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
